// SPDX-FileCopyrightText: 2026 SPHARX Ltd.
// SPDX-License-Identifier: AGPL-3.0-or-later OR Apache-2.0

//! 构建期从 C 侧唯一权威 airy_run_stream.h 生成 Rust 事件协议常量（SSoT）。
//!
//! 背景：M1-1d §2.4 协议 schema 唯一权威落在
//! agentrt/commons/include/airy_run_stream.h，gateway 编码器与 sdk-rust
//! 解码器必须共引同一份定义，禁止在 Rust 侧手写 wire 键名字面量。
//! 本脚本解析该头文件中的 `#define AIRY_RS_*`，生成 `pub const` 常量文件
//! （OUT_DIR/run_stream_gen.rs），run_stream.rs 经 include!() 共引。
//!
//! fail-closed 门禁：头文件缺失或解析出 0 个宏即构建失败（panic），
//! 杜绝"契约头漂移后 Rust 侧静默降级"。

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    let header = locate_header();
    println!("cargo:rerun-if-changed={}", header.display());

    let content = fs::read_to_string(&header)
        .unwrap_or_else(|e| panic!("run_stream schema header unreadable: {} ({})", header.display(), e));

    let generated = generate(&content);
    if generated.is_empty() {
        panic!(
            "run_stream schema header parsed zero AIRY_RS_* macros: {}",
            header.display()
        );
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    fs::write(out_dir.join("run_stream_gen.rs"), generated).expect("failed to write run_stream_gen.rs");
}

/// 定位 airy_run_stream.h：优先 env AGENTRT_RS_RUN_STREAM_H，
/// 否则 monorepo 默认布局（sdk-rust 上一级 agentrt 仓库）。
fn locate_header() -> PathBuf {
    if let Ok(path) = env::var("AGENTRT_RS_RUN_STREAM_H") {
        let p = PathBuf::from(&path);
        if p.is_file() {
            return p;
        }
        panic!("AGENTRT_RS_RUN_STREAM_H set but not a file: {path}");
    }

    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    /* sdk-rust 与 agentrt 同级（agent-workload/ 下），monorepo 布局 */
    let candidate = Path::new(&manifest).join("../../agentrt/commons/include/airy_run_stream.h");
    if candidate.is_file() {
        return candidate;
    }

    panic!(
        "run_stream schema header not found (tried {}). \
         Set AGENTRT_RS_RUN_STREAM_H to the airy_run_stream.h path.",
        candidate.display()
    );
}

/// 解析 #define AIRY_RS_* 宏并生成 Rust 常量（统一收纳于 gen 子模块，
/// 与 run_stream 模块自身符号隔离）。
fn generate(content: &str) -> String {
    let mut out = String::new();
    out.push_str("// @generated by sdk-rust/build.rs from commons/include/airy_run_stream.h\n");
    out.push_str("// DO NOT EDIT. 字段键/事件类型常量以 C 侧 schema 为唯一权威（SSoT）。\n\n");
    out.push_str("pub mod gen {\n");

    let mut count = 0usize;
    for line in content.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("#define ") else {
            continue;
        };
        let mut parts = rest.splitn(2, char::is_whitespace);
        let name = parts.next().unwrap_or("");
        let value = parts.next().unwrap_or("").trim();
        if !name.starts_with("AIRY_RS_") || value.is_empty() {
            continue;
        }
        if value.starts_with('"') && value.ends_with('"') {
            out.push_str(&format!("    pub const {name}: &str = {value};\n"));
            count += 1;
        } else if value.chars().all(|c| c.is_ascii_digit()) {
            out.push_str(&format!("    pub const {name}: i64 = {value};\n"));
            count += 1;
        }
    }

    out.push_str("}\n");
    let _ = count; /* fail-closed 由调用方按空串判断 */
    out
}
